use std::any::{Any, TypeId};
use std::collections::HashMap;
use std::time::Instant;

use uuid::Uuid;

/// Defines a message type and its expected reply.
///
/// Implemented on the MESSAGE, not the actor — decouples message definition
/// from handling, allowing the same message to be handled by different actors.
pub trait Message: Send + 'static {
    /// The reply type. Use `()` for fire-and-forget (tell) messages.
    type Reply: Send + 'static;
}

/// A header value that can be stored in the Headers map.
/// Locally: stored by TypeId for type-safe access.
/// Remotely: serialized via to_bytes() with header_name() as key.
pub trait HeaderValue: Send + Sync + 'static {
    /// Stable, unique name for wire transport.
    fn header_name(&self) -> &'static str;

    /// Serialize for remote transport. None = local-only header.
    fn to_bytes(&self) -> Option<Vec<u8>>;

    /// Downcast support.
    fn as_any(&self) -> &dyn Any;
}

/// Type-safe header collection keyed by TypeId.
#[derive(Default)]
pub struct Headers {
    map: HashMap<TypeId, Box<dyn HeaderValue>>,
}

impl Headers {
    pub fn new() -> Self {
        Self { map: HashMap::new() }
    }

    /// Insert a typed header. Replaces any existing header of the same type.
    pub fn insert<H: HeaderValue>(&mut self, value: H) {
        self.map.insert(TypeId::of::<H>(), Box::new(value));
    }

    /// Get a reference to a typed header, if present.
    pub fn get<H: HeaderValue + 'static>(&self) -> Option<&H> {
        self.map
            .get(&TypeId::of::<H>())
            .and_then(|v| v.as_any().downcast_ref::<H>())
    }

    /// Remove a typed header, returning it if present.
    pub fn remove<H: HeaderValue + 'static>(&mut self) -> Option<Box<dyn HeaderValue>> {
        self.map.remove(&TypeId::of::<H>())
    }

    /// Check if the headers collection is empty.
    pub fn is_empty(&self) -> bool {
        self.map.is_empty()
    }

    /// Number of headers.
    pub fn len(&self) -> usize {
        self.map.len()
    }
}

impl std::fmt::Debug for Headers {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Headers")
            .field("count", &self.map.len())
            .finish()
    }
}

/// Globally unique identifier for a message, auto-assigned by the runtime.
/// Uses UUID v4 for uniqueness across nodes without coordination.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MessageId(pub Uuid);

impl MessageId {
    /// Generate a new globally unique MessageId (UUID v4).
    pub fn next() -> Self {
        Self(Uuid::new_v4())
    }
}

impl std::fmt::Display for MessageId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "msg-{}", self.0)
    }
}

/// Read-only headers auto-generated by the runtime.
/// Interceptors can read these but cannot modify or remove them.
#[derive(Debug, Clone)]
pub struct RuntimeHeaders {
    /// Unique message ID — auto-assigned by the runtime for every message.
    pub message_id: MessageId,
    /// When the runtime received/created this message.
    pub timestamp: Instant,
}

impl RuntimeHeaders {
    /// Create new RuntimeHeaders with a fresh MessageId and current timestamp.
    pub fn new() -> Self {
        Self {
            message_id: MessageId::next(),
            timestamp: Instant::now(),
        }
    }
}

impl Default for RuntimeHeaders {
    fn default() -> Self {
        Self::new()
    }
}

/// An envelope wrapping a message body with headers.
/// Used for LOCAL sends — the message is passed by move (no serialization).
#[derive(Debug)]
pub struct Envelope<M> {
    /// Runtime-managed, read-only headers (MessageId, timestamp).
    pub runtime_headers: RuntimeHeaders,
    /// User/interceptor-managed headers (trace context, priority, custom).
    pub headers: Headers,
    /// The message body.
    pub body: M,
}

impl<M> Envelope<M> {
    /// Create a new envelope with default runtime headers.
    pub fn new(body: M) -> Self {
        Self {
            runtime_headers: RuntimeHeaders::new(),
            headers: Headers::new(),
            body,
        }
    }

    /// Create a new envelope with custom headers.
    pub fn with_headers(body: M, headers: Headers) -> Self {
        Self {
            runtime_headers: RuntimeHeaders::new(),
            headers,
            body,
        }
    }
}

/// Built-in priority header. Used by priority mailboxes and interceptors.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Priority(pub u8);

impl Priority {
    pub const CRITICAL: Self = Self(0);
    pub const HIGH: Self = Self(64);
    pub const NORMAL: Self = Self(128);
    pub const LOW: Self = Self(192);
    pub const BACKGROUND: Self = Self(255);
}

impl Default for Priority {
    fn default() -> Self { Self::NORMAL }
}

impl HeaderValue for Priority {
    fn header_name(&self) -> &'static str { "dactor.Priority" }

    fn to_bytes(&self) -> Option<Vec<u8>> {
        Some(vec![self.0])
    }

    fn as_any(&self) -> &dyn Any { self }
}

impl std::fmt::Display for Priority {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.0 {
            0 => write!(f, "CRITICAL"),
            64 => write!(f, "HIGH"),
            128 => write!(f, "NORMAL"),
            192 => write!(f, "LOW"),
            255 => write!(f, "BACKGROUND"),
            n => write!(f, "Priority({})", n),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Increment(u64);
    impl Message for Increment {
        type Reply = ();
    }

    struct GetCount;
    impl Message for GetCount {
        type Reply = u64;
    }

    struct Reset;
    impl Message for Reset {
        type Reply = u64;
    }

    #[test]
    fn test_message_reply_types() {
        fn assert_reply_unit<M: Message<Reply = ()>>() {}
        fn assert_reply_u64<M: Message<Reply = u64>>() {}

        assert_reply_unit::<Increment>();
        assert_reply_u64::<GetCount>();
        assert_reply_u64::<Reset>();
    }

    #[test]
    fn test_headers_insert_get() {
        let mut headers = Headers::new();
        headers.insert(Priority::HIGH);

        let p = headers.get::<Priority>().unwrap();
        assert_eq!(*p, Priority::HIGH);
    }

    #[test]
    fn test_headers_insert_replace() {
        let mut headers = Headers::new();
        headers.insert(Priority::LOW);
        headers.insert(Priority::CRITICAL);

        let p = headers.get::<Priority>().unwrap();
        assert_eq!(*p, Priority::CRITICAL);
    }

    #[test]
    fn test_headers_remove() {
        let mut headers = Headers::new();
        headers.insert(Priority::NORMAL);
        assert!(!headers.is_empty());

        headers.remove::<Priority>();
        assert!(headers.is_empty());
        assert!(headers.get::<Priority>().is_none());
    }

    #[test]
    fn test_headers_get_missing() {
        let headers = Headers::new();
        assert!(headers.get::<Priority>().is_none());
    }

    #[test]
    fn test_multiple_header_types() {
        #[derive(Debug)]
        struct TraceId(String);

        impl HeaderValue for TraceId {
            fn header_name(&self) -> &'static str { "app.TraceId" }
            fn to_bytes(&self) -> Option<Vec<u8>> { Some(self.0.as_bytes().to_vec()) }
            fn as_any(&self) -> &dyn Any { self }
        }

        let mut headers = Headers::new();
        headers.insert(Priority::HIGH);
        headers.insert(TraceId("abc-123".into()));

        assert_eq!(headers.len(), 2);
        assert_eq!(headers.get::<Priority>().unwrap().0, 64);
        assert_eq!(headers.get::<TraceId>().unwrap().0, "abc-123");
    }

    #[test]
    fn test_message_id_uniqueness() {
        let ids: Vec<MessageId> = (0..1000).map(|_| MessageId::next()).collect();
        let unique: std::collections::HashSet<_> = ids.iter().collect();
        assert_eq!(unique.len(), 1000);
    }

    #[test]
    fn test_message_id_display() {
        let id = MessageId::next();
        let display = format!("{}", id);
        assert!(display.starts_with("msg-"));
        assert!(display.len() > 10); // UUID is 36 chars
    }

    #[test]
    fn test_runtime_headers_creation() {
        let rh1 = RuntimeHeaders::new();
        let rh2 = RuntimeHeaders::new();
        assert_ne!(rh1.message_id, rh2.message_id);
    }

    #[test]
    fn test_envelope_construction() {
        let envelope = Envelope::new("hello");
        assert_eq!(envelope.body, "hello");
        assert!(envelope.headers.is_empty());
    }

    #[test]
    fn test_envelope_with_headers() {
        let mut headers = Headers::new();
        headers.insert(Priority::CRITICAL);

        let envelope = Envelope::with_headers(42u64, headers);
        assert_eq!(envelope.body, 42);
        assert_eq!(envelope.headers.get::<Priority>().unwrap().0, 0);
    }

    #[test]
    fn test_priority_constants() {
        assert!(Priority::CRITICAL.0 < Priority::HIGH.0);
        assert!(Priority::HIGH.0 < Priority::NORMAL.0);
        assert!(Priority::NORMAL.0 < Priority::LOW.0);
        assert!(Priority::LOW.0 < Priority::BACKGROUND.0);
    }

    #[test]
    fn test_priority_display() {
        assert_eq!(format!("{}", Priority::CRITICAL), "CRITICAL");
        assert_eq!(format!("{}", Priority::HIGH), "HIGH");
        assert_eq!(format!("{}", Priority::NORMAL), "NORMAL");
        assert_eq!(format!("{}", Priority(100)), "Priority(100)");
    }

    #[test]
    fn test_priority_to_bytes() {
        let p = Priority::HIGH;
        assert_eq!(p.to_bytes(), Some(vec![64]));
        assert_eq!(p.header_name(), "dactor.Priority");
    }

    #[test]
    fn test_headers_len() {
        let mut headers = Headers::new();
        assert_eq!(headers.len(), 0);
        headers.insert(Priority::NORMAL);
        assert_eq!(headers.len(), 1);
    }

    #[test]
    fn test_local_only_header() {
        #[derive(Debug)]
        struct HandlerStartTime(Instant);

        impl HeaderValue for HandlerStartTime {
            fn header_name(&self) -> &'static str { "dactor.internal.HandlerStartTime" }
            fn to_bytes(&self) -> Option<Vec<u8>> { None }
            fn as_any(&self) -> &dyn Any { self }
        }

        let mut headers = Headers::new();
        headers.insert(HandlerStartTime(Instant::now()));

        let h = headers.get::<HandlerStartTime>().unwrap();
        assert!(h.to_bytes().is_none());
    }
}
